Loaded module: python3/3.6.2
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
Traceback (most recent call last):
  File "dataset/make.py", line 112, in <module>
    mel, mag = spec_feature_extraction(path)
  File "dataset/make.py", line 49, in spec_feature_extraction
    mel, mag = get_spectrograms(wav_file)
  File "/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/dataset/tacotron/utils.py", line 34, in get_spectrograms
    y, sr = librosa.load(fpath, sr=hp.sr)
  File "/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/librosa/core/audio.py", line 129, in load
    with sf.SoundFile(path) as sf_desc:
  File "/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/work1/s183921/fagprojekt2020/preprocess/spraakbanken/vae/preprocess_vae/lib/python3.6/site-packages/soundfile.py", line 1175, in _open
    file_ptr = openfunction(file, mode_int, self._info)
KeyboardInterrupt
Traceback (most recent call last):
  File "dataset/reduce.py", line 10, in <module>
    data = pickle.load(f)
EOFError: Ran out of input
Traceback (most recent call last):
  File "dataset/segments.py", line 14, in <module>
    data = pickle.load(f)
EOFError: Ran out of input
Traceback (most recent call last):
  File "dataset/segments.py", line 13, in <module>
    with open(pickle_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/work1/s183921/preprocessed_data/vae/spraakbanken/in_test.pkl'
Traceback (most recent call last):
  File "dataset/segments.py", line 13, in <module>
    with open(pickle_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/work1/s183921/preprocessed_data/vae/spraakbanken/out_test.pkl'
